import { UserPlus } from "lucide-react";
import { workspaceMutationAction } from "../../actions";
import { Feedback, OperatorPageHeader } from "@/components/operator/page-header";
import { requireLibraryAdministrator } from "@/lib/auth/authorization";
import { getWorkspaceData } from "@/lib/operator/workspace";

type Operator = { id: string; name: string; roles: string[]; globalStatus: string; roomStatus: string };
export default async function OperatorsPage({ params, searchParams }: { params: Promise<{ libraryCode: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ libraryCode }, query] = await Promise.all([params, searchParams]); await requireLibraryAdministrator(libraryCode); const data=await getWorkspaceData(libraryCode,"operators"); const operators=(data.operators??[]) as Operator[]; const disabled=Boolean(data.demo);
  return <section className="operator-page-v3"><OperatorPageHeader title="Operators" description="Invite by email and manage roles inside this Library Room only." actions={<details className="create-popover"><summary className="button button-primary"><UserPlus aria-hidden="true"/>Add operator</summary><div><form action={workspaceMutationAction} className="popover-form"><input type="hidden" name="libraryCode" value={libraryCode}/><input type="hidden" name="operation" value="operator_assign"/><h2>Invite or assign room access</h2><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Display name<input name="displayName" required maxLength={160}/></label><label>Role<select name="role"><option value="librarian">Librarian</option><option value="administrator">Administrator</option></select></label><p className="field-note">New accounts receive a supported Supabase Auth invitation. Existing accounts are linked without changing their global lifecycle status.</p><button className="button button-primary" disabled={disabled}>Assign role</button></form></div></details>}/><Feedback error={query.error??data.error} success={query.success}/><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Operator</th><th>Roles in this library</th><th>Global profile</th><th>Room access</th><th>Control</th></tr></thead><tbody>{operators.map((operator)=><tr key={operator.id}><td><strong>{operator.name}</strong></td><td>{operator.roles.map((role)=>role[0].toUpperCase()+role.slice(1)).join(" · ")}</td><td><span className={`status-dot ${operator.globalStatus==="active"?"status-success":"status-danger"}`}>{operator.globalStatus}</span></td><td><span className={`status-dot ${operator.roomStatus==="active"?"status-success":"status-neutral"}`}>{operator.roomStatus}</span></td><td><form action={workspaceMutationAction}><input type="hidden" name="libraryCode" value={libraryCode}/><input type="hidden" name="operation" value="operator_status"/><input type="hidden" name="profileId" value={operator.id}/><input type="hidden" name="status" value={operator.roomStatus==="active"?"inactive":"active"}/><button className="button button-small button-secondary" disabled={disabled || operator.globalStatus!=="active"}>{operator.roomStatus==="active"?"Remove room access":"Restore room access"}</button></form></td></tr>)}</tbody></table>{!operators.length&&!data.error?<div className="table-empty">No room operators found</div>:null}</div></section>;
}
