import Link from "next/link";
import { MoreHorizontal } from "lucide-react";
import { workspaceMutationAction } from "../actions";
import { Feedback, OperatorPageHeader } from "@/components/operator/page-header";
import { OperatorToolbar } from "@/components/operator/toolbar";
import { getWorkspaceData } from "@/lib/operator/workspace";

type Member = { id: string; name: string; identifier: string; kind: string; context: string; activeLoans: number; status: string };
export default async function MembersPage({ params, searchParams }: { params: Promise<{ libraryCode: string }>; searchParams: Promise<{ q?: string; error?: string; success?: string }> }) {
  const [{ libraryCode }, query] = await Promise.all([params, searchParams]); const data = await getWorkspaceData(libraryCode, "members", query.q); const members = (data.members ?? []) as Member[];
  return <section className="operator-page-v3"><OperatorPageHeader title="Members" description="Borrowing identity, academic context, and current eligibility at a glance." /><Feedback error={query.error ?? data.error} success={query.success} /><OperatorToolbar query={query.q} addLabel="Add member"><form action={workspaceMutationAction} className="popover-form"><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value="member_create" /><h2>Create member</h2><label>Display name<input name="displayName" required maxLength={200} /></label><label>Member kind<select name="memberKind" defaultValue="student"><option value="student">Student</option><option value="teacher">Teacher</option><option value="staff">Staff</option><option value="other">Other</option></select></label><button className="button button-primary" type="submit" disabled={Boolean(data.demo)}>Create member</button></form></OperatorToolbar><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Member</th><th>Kind</th><th>Academic context</th><th>Borrowing</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{members.map((member) => <tr key={member.id}><td><Link href={`/operator/${libraryCode}/members/${member.id}`}><strong>{member.name}</strong><small>{member.identifier}</small></Link></td><td>{member.kind}</td><td>{member.context}</td><td>{member.activeLoans} active</td><td><span className="status-dot status-success">{member.status}</span></td><td><Link className="icon-button" href={`/operator/${libraryCode}/members/${member.id}`} aria-label={`Open ${member.name}`}><MoreHorizontal aria-hidden="true" /></Link></td></tr>)}</tbody></table>{!members.length && !data.error ? <div className="table-empty">No matching members</div> : null}</div></section>;
}
