"use server";

import { redirect } from "next/navigation";
import { assertAdministrator } from "@/lib/auth/authorization";
import { formValue } from "@/lib/operator/forms";
import { asOperatorRpcClient, rpcErrorMessage } from "@/lib/operator/rpc";
import { createSupabaseServerClient } from "@/lib/supabase/server";
function fail(message: string): never { redirect(`/operator/settings?error=${encodeURIComponent(message)}`); }
export async function saveSettingAction(formData: FormData) { await assertAdministrator(); const supabase = asOperatorRpcClient(await createSupabaseServerClient()); const key = formValue(formData, "key"); const isBoolean = key === "fines_enabled"; const raw = formValue(formData, "value"); const { error } = await supabase.rpc("admin_upsert_setting", { p_setting_key: key, p_boolean_value: isBoolean ? raw === "true" : null, p_integer_value: isBoolean || key === "daily_fine_rate_minor" ? null : Number(raw), p_money_minor_value: key === "daily_fine_rate_minor" ? Math.round(Number(raw) * 100) : null }); if (error) fail(rpcErrorMessage(error)); redirect(`/operator/settings?success=${encodeURIComponent("Setting saved")}`); }
export async function saveAcademicSessionAction(formData: FormData) { await assertAdministrator(); const supabase = asOperatorRpcClient(await createSupabaseServerClient()); const { error } = await supabase.rpc("admin_upsert_academic_session", { p_id: null, p_session_code: formValue(formData, "sessionCode"), p_display_label: formValue(formData, "displayLabel"), p_starts_on: formValue(formData, "startsOn"), p_ends_on: formValue(formData, "endsOn"), p_status: formValue(formData, "status") }); if (error) fail(rpcErrorMessage(error)); redirect(`/operator/settings?success=${encodeURIComponent("Academic session saved")}`); }
export async function saveGradeAction(formData: FormData) { await assertAdministrator(); const supabase = asOperatorRpcClient(await createSupabaseServerClient()); const { error } = await supabase.rpc("admin_upsert_grade", { p_id: null, p_grade_code: formValue(formData, "gradeCode"), p_display_name: formValue(formData, "displayName"), p_sort_order: Number(formValue(formData, "sortOrder") || 0) }); if (error) fail(rpcErrorMessage(error)); redirect(`/operator/settings?success=${encodeURIComponent("Grade saved")}`); }
export async function saveSectionAction(formData: FormData) { await assertAdministrator(); const supabase = asOperatorRpcClient(await createSupabaseServerClient()); const { error } = await supabase.rpc("admin_upsert_section", { p_id: null, p_section_code: formValue(formData, "sectionCode"), p_display_name: formValue(formData, "displayName"), p_sort_order: Number(formValue(formData, "sortOrder") || 0) }); if (error) fail(rpcErrorMessage(error)); redirect(`/operator/settings?success=${encodeURIComponent("Section saved")}`); }
