import { BookKey, Building2, CalendarRange, Globe2 } from "lucide-react";
import { workspaceMutationAction } from "../actions";
import { Feedback, OperatorPageHeader } from "@/components/operator/page-header";
import { MutationRequestId, MutationSubmitButton } from "@/components/operator/mutation-controls";
import { requireLibraryAdministrator } from "@/lib/auth/authorization";
import { formatMinorUnitsForInput, moneyInputStep } from "@/lib/i18n/library-localization";
import { getWorkspaceData } from "@/lib/operator/workspace";

type Setting = { setting_key: string; value_kind: "boolean" | "integer" | "money_minor"; boolean_value: boolean | null; integer_value: number | null; money_minor_value: number | null };
type Session = { id: string; session_code: string; display_label: string; starts_on: string; ends_on: string; status: string };
type Academic = { id: string; grade_code?: string; section_code?: string; display_name: string; sort_order: number };
const labels: Record<string, string> = { fines_enabled: "Fines enabled", default_loan_period_days: "Default loan period (days)", checkout_limit: "Checkout limit", renewal_limit: "Renewal limit", grace_period_days: "Fine grace period (days)", daily_fine_rate_minor: "Daily fine rate", overdue_renewal_allowed: "Allow overdue renewals", librarian_waiver_allowed: "Allow librarian waivers" };

export default async function SettingsPage({ params, searchParams }: { params: Promise<{ libraryCode: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const [{ libraryCode }, query] = await Promise.all([params, searchParams]);
  const context = await requireLibraryAdministrator(libraryCode);
  const data = await getWorkspaceData(libraryCode, "settings");
  const settings = (data.typedSettings ?? []) as Setting[];
  const disabled = Boolean(data.demo || data.error);
  return <section className="operator-page-v3">
    <OperatorPageHeader title="Settings" description="Library identity, localization, academic structure, and policies enforced by the database." />
    <Feedback error={query.error ?? data.error} success={query.success} />
    <div className="settings-layout"><nav aria-label="Settings sections"><a href="#identity"><Building2 aria-hidden="true" />Library identity</a><a href="#localization"><Globe2 aria-hidden="true" />Localization</a><a href="#academic"><CalendarRange aria-hidden="true" />Academic structure</a><a href="#circulation"><BookKey aria-hidden="true" />Circulation policy</a></nav><div>
      <section id="identity" className="settings-section"><h2>Library identity</h2><p>The public code remains stable so published links do not break.</p><form action={workspaceMutationAction} className="form-grid"><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value="library_update" /><MutationRequestId /><label>Library display name<input name="displayName" defaultValue={context.libraryName} required maxLength={160} disabled={disabled} /></label><label>Library code<input className="code-field" value={libraryCode} readOnly /></label><MutationSubmitButton idleLabel="Save identity" className="button button-secondary" disabled={disabled} /></form></section>
      <section id="localization" className="settings-section"><h2>Localization</h2><p>Currency changes never convert values. They remain available only while all monetary records and settings are zero.</p><form action={workspaceMutationAction} className="form-grid"><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value="library_localization_update" /><MutationRequestId /><label>Currency<input name="currencyCode" defaultValue={context.currencyCode} minLength={3} maxLength={3} pattern="[A-Za-z]{3}" required disabled={disabled} /></label><label>Locale<input name="localeCode" defaultValue={context.localeCode} minLength={2} maxLength={64} required disabled={disabled} /></label><label>Timezone<input name="timeZone" defaultValue={context.timeZone} minLength={3} maxLength={64} required disabled={disabled} /></label><MutationSubmitButton idleLabel="Save localization" className="button button-secondary" disabled={disabled} /></form></section>
      <section id="circulation" className="settings-section"><h2>Circulation and fine policy</h2><div className="settings-list">{settings.map((setting) => <form action={workspaceMutationAction} key={setting.setting_key}><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value="setting_update" /><input type="hidden" name="settingKey" value={setting.setting_key} /><input type="hidden" name="valueKind" value={setting.value_kind} /><MutationRequestId /><label><span><strong>{labels[setting.setting_key] ?? setting.setting_key}{setting.value_kind === "money_minor" ? ` (${context.currencyCode})` : ""}</strong><small>Applied only inside this Library Room.</small></span>{setting.value_kind === "boolean" ? <select name="settingValue" defaultValue={String(setting.boolean_value)} disabled={disabled}><option value="false">Disabled</option><option value="true">Enabled</option></select> : <input name="settingValue" type="number" min={setting.setting_key === "default_loan_period_days" ? 1 : 0} step={setting.value_kind === "money_minor" ? moneyInputStep(context.currencyCode) ?? "0.01" : "1"} defaultValue={setting.value_kind === "money_minor" ? formatMinorUnitsForInput(setting.money_minor_value, context.currencyCode) : Number(setting.integer_value ?? 0)} disabled={disabled} />}</label><MutationSubmitButton idleLabel="Save" className="button button-small button-secondary" disabled={disabled} /></form>)}</div></section>
      <section id="academic" className="settings-section"><h2>Academic structure</h2><p>Students require a current active session, grade, and section. Historical enrollment records are preserved.</p><div className="operator-grid"><form action={workspaceMutationAction} className="popover-form"><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value="academic_session_save" /><MutationRequestId /><h3>Add academic session</h3><label>Code<input name="sessionCode" required maxLength={40} /></label><label>Label<input name="displayLabel" required maxLength={120} /></label><div className="form-grid"><label>Starts<input name="startsOn" type="date" required /></label><label>Ends<input name="endsOn" type="date" required /></label></div><label>Status<select name="status"><option value="planned">Planned</option><option value="active">Active</option><option value="closed">Closed</option><option value="archived">Archived</option></select></label><MutationSubmitButton idleLabel="Save session" pendingLabel="Saving…" disabled={disabled} /></form><AcademicForm libraryCode={libraryCode} kind="grade" disabled={disabled} /><AcademicForm libraryCode={libraryCode} kind="section" disabled={disabled} /></div><AcademicTables sessions={(data.sessions ?? []) as Session[]} grades={(data.grades ?? []) as Academic[]} sections={(data.sections ?? []) as Academic[]} /></section>
    </div></div>
  </section>;
}

function AcademicForm({ libraryCode, kind, disabled }: { libraryCode: string; kind: "grade" | "section"; disabled: boolean }) { const title = kind === "grade" ? "grade / class" : "section"; return <form action={workspaceMutationAction} className="popover-form"><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value={`${kind}_save`} /><MutationRequestId /><h3>Add {title}</h3><label>Code<input name={kind === "grade" ? "gradeCode" : "sectionCode"} required maxLength={40} /></label><label>Display name<input name="displayName" required maxLength={120} /></label><label>Sort order<input name="sortOrder" type="number" min="0" defaultValue="0" /></label><MutationSubmitButton idleLabel={`Save ${title}`} pendingLabel="Saving…" disabled={disabled} /></form>; }
function AcademicTables({ sessions, grades, sections }: { sessions: Session[]; grades: Academic[]; sections: Academic[] }) { return <div className="academic-summary"><article><h3>Sessions</h3>{sessions.map((item) => <p key={item.id}><strong>{item.display_label}</strong><span>{item.session_code} · {item.status} · {item.starts_on}–{item.ends_on}</span></p>)}</article><article><h3>Grades</h3>{grades.map((item) => <p key={item.id}><strong>{item.display_name}</strong><span>{item.grade_code}</span></p>)}</article><article><h3>Sections</h3>{sections.map((item) => <p key={item.id}><strong>{item.display_name}</strong><span>{item.section_code}</span></p>)}</article></div>; }
