import Link from "next/link";
import { ArrowLeft, MapPin, PackageCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { CopyForm } from "@/components/operator/copy-form";
import { Feedback, OperatorPageHeader } from "@/components/operator/page-header";
import { getWorkspaceData } from "@/lib/operator/workspace";

type Copy = { id: string; book_id: string; accession_number: string; barcode?: string; location_id?: string; acquired_on?: string; acquisition_source?: string; replacement_cost_minor?: number; condition_status: string; operational_state: string; updated_at: string }; type Summary = { id: string; accession: string; title: string; location: string; condition: string; state: string }; type BookOption = { id: string; title: string }; type Location = { id: string; display_name: string; location_code: string };
export default async function CopyWorkspacePage({ params, searchParams }: { params: Promise<{ libraryCode: string; id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) { const [{ libraryCode, id }, query] = await Promise.all([params, searchParams]); const data = await getWorkspaceData(libraryCode, "inventory", "", id); const copy = data.copy as Copy | undefined; const summary = ((data.copies ?? []) as Summary[]).find((item) => item.id === id); const room = data.room as { currencyCode?: string; localeCode?: string } | undefined; if (!copy || !summary) notFound(); return <section className="operator-page-v3 detail-workspace"><Link className="back-link" href={`/operator/${libraryCode}/inventory`}><ArrowLeft aria-hidden="true" />Inventory</Link><OperatorPageHeader title={summary.accession} description={summary.title} /><Feedback error={query.error ?? data.error} success={query.success} /><div className="detail-status-rail"><span className={`status-dot ${summary.state === "Available" ? "status-success" : "status-info"}`}>{summary.state}</span><span><PackageCheck aria-hidden="true" />{summary.condition} condition</span><span><MapPin aria-hidden="true" />{summary.location}</span></div><section className="detail-form-section"><h2>Copy record</h2><CopyForm libraryCode={libraryCode} currencyCode={room?.currencyCode} localeCode={room?.localeCode} copy={copy} books={(data.bookOptions ?? []) as BookOption[]} locations={(data.locations ?? []) as Location[]} disabled={Boolean(data.demo)} /></section></section>; }
