import { NextResponse } from "next/server";
import { assertOperator } from "@/lib/auth/authorization";
import { asOperatorRpcClient } from "@/lib/operator/rpc";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const reports: Record<string, string> = { circulation: "report_circulation_filtered", overdue: "report_overdue_filtered", popular: "report_popular_books_filtered", members: "report_member_activity_filtered", inventory: "report_inventory_filtered", fines: "report_fines_filtered" };
function csvCell(value: unknown) { const raw = String(value ?? ""); const safe = /^[\u0000-\u0020]*[=+@-]/.test(raw) ? `'${raw}` : raw; return `"${safe.replaceAll('"', '""')}"`; }
function dateOrNull(value: string | null) { return value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : null; }
function args(kind: string, params: URLSearchParams) { const from = dateOrNull(params.get("from")); const to = dateOrNull(params.get("to")); const q = params.get("q") ?? ""; if (kind === "overdue") return { p_as_of: to, p_query: q }; if (kind === "popular") return { p_from: from, p_to: to }; if (kind === "members") return { p_from: from, p_to: to, p_query: q }; if (kind === "inventory") return { p_status: params.get("status") || null, p_location_id: null }; if (kind === "fines") return { p_from: from, p_to: to, p_query: q, p_outstanding_only: params.get("outstanding") === "true" }; return { p_from: from, p_to: to, p_query: q }; }
export async function GET(request: Request) { await assertOperator(); const params = new URL(request.url).searchParams; const kind = params.get("kind") && reports[params.get("kind")!] ? params.get("kind")! : "circulation"; const { data, error } = await asOperatorRpcClient(await createSupabaseServerClient()).rpc(reports[kind], args(kind, params)); if (error) return NextResponse.json({ error: "Report unavailable" }, { status: 400 }); const rows = Array.isArray(data) ? data as Array<Record<string, unknown>> : []; const columns = rows.length ? Object.keys(rows[0]) : []; const body = [columns, ...rows.map((row) => columns.map((column) => row[column]))].map((row) => row.map(csvCell).join(",")).join("\r\n"); return new NextResponse(body, { headers: { "content-type": "text/csv; charset=utf-8", "content-disposition": `attachment; filename="granthsetu-${kind}.csv"`, "cache-control": "no-store" } }); }
