"use client";

import { useMemo, useState } from "react";
import { BookCheck, CalendarDays, Check, Clock3, RefreshCw, RotateCcw, Search, UserRound } from "lucide-react";
import { workspaceMutationAction } from "@/app/operator/[libraryCode]/actions";

type Member = { id: string; name: string; identifier: string; context: string; activeLoans: number; overdueLoans: number };
type Copy = { id: string; title: string; author: string; accession: string; location: string; state: string };
type Loan = { id: string; member: string; identifier: string; title: string; accession: string; due: string; overdue: boolean };

export function CirculationWorkbench({ libraryCode, members, copies, loans, disabled = false }: { libraryCode: string; members: Member[]; copies: Copy[]; loans: Loan[]; disabled?: boolean }) {
  const [mode, setMode] = useState<"issue" | "renew" | "return">("issue"); const [memberQuery, setMemberQuery] = useState(""); const [copyQuery, setCopyQuery] = useState(""); const [loanQuery, setLoanQuery] = useState("");
  const [memberId, setMemberId] = useState(""); const [copyId, setCopyId] = useState(""); const [loanId, setLoanId] = useState("");
  const visibleMembers = useMemo(() => members.filter((item) => `${item.name} ${item.identifier} ${item.context}`.toLowerCase().includes(memberQuery.toLowerCase())), [memberQuery, members]);
  const visibleCopies = useMemo(() => copies.filter((item) => `${item.title} ${item.author} ${item.accession}`.toLowerCase().includes(copyQuery.toLowerCase())), [copyQuery, copies]);
  const visibleLoans = useMemo(() => loans.filter((item) => `${item.member} ${item.identifier} ${item.title} ${item.accession}`.toLowerCase().includes(loanQuery.toLowerCase())), [loanQuery, loans]);
  const member = members.find((item) => item.id === memberId); const copy = copies.find((item) => item.id === copyId); const loan = loans.find((item) => item.id === loanId);
  return <div className="circulation-command"><div className="mode-tabs" role="tablist" aria-label="Circulation operation"><button role="tab" aria-selected={mode === "issue"} onClick={() => setMode("issue")}><BookCheck aria-hidden="true" />Issue</button><button role="tab" aria-selected={mode === "renew"} onClick={() => setMode("renew")}><RefreshCw aria-hidden="true" />Renew</button><button role="tab" aria-selected={mode === "return"} onClick={() => setMode("return")}><RotateCcw aria-hidden="true" />Return</button></div>
    {mode === "issue" ? <form action={workspaceMutationAction} className="issue-grid"><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value="issue" /><input type="hidden" name="memberId" value={memberId} /><input type="hidden" name="copyId" value={copyId} />
      <SelectionPanel step="1" title="Select member" query={memberQuery} onQuery={setMemberQuery} placeholder="Name, member ID, class or roll"><div className="selection-list">{visibleMembers.map((item) => <button key={item.id} type="button" aria-pressed={memberId === item.id} onClick={() => setMemberId(item.id)}><span className="selection-avatar">{item.name.slice(0, 2)}</span><span><strong>{item.name}</strong><small>{item.identifier} · {item.context}</small></span>{memberId === item.id ? <Check aria-hidden="true" /> : null}</button>)}</div>{member ? <div className="eligibility-summary"><h3>Eligibility</h3><p><Check aria-hidden="true" />Active member</p><p className={member.overdueLoans ? "is-warning" : ""}>{member.overdueLoans ? <Clock3 aria-hidden="true" /> : <Check aria-hidden="true" />}{member.overdueLoans} overdue · {member.activeLoans} active loans</p></div> : <Prompt icon={UserRound} text="Choose one borrower to inspect eligibility." />}</SelectionPanel>
      <SelectionPanel step="2" title="Select book copy" query={copyQuery} onQuery={setCopyQuery} placeholder="Title, author, ISBN or accession"><div className="selection-list">{visibleCopies.map((item) => <button key={item.id} type="button" aria-pressed={copyId === item.id} onClick={() => setCopyId(item.id)}><span className="copy-glyph">GS</span><span><strong>{item.title}</strong><small>{item.author} · {item.accession}</small></span>{copyId === item.id ? <Check aria-hidden="true" /> : null}</button>)}</div>{copy ? <div className="copy-summary"><h3>Selected copy</h3><dl><div><dt>Accession</dt><dd>{copy.accession}</dd></div><div><dt>Location</dt><dd>{copy.location}</dd></div><div><dt>State</dt><dd><span className="status-dot status-success">{copy.state}</span></dd></div></dl></div> : <Prompt icon={BookCheck} text="Choose one physical copy. Availability is verified again on issue." />}</SelectionPanel>
      <aside className="transaction-summary"><p>3</p><h2>Confirm issue</h2>{member && copy ? <><div><span>Member</span><strong>{member.name}</strong><small>{member.identifier}</small></div><div><span>Book copy</span><strong>{copy.title}</strong><small>{copy.accession}</small></div><label>Note (optional)<input name="notes" maxLength={2000} /></label><div className="due-preview"><CalendarDays aria-hidden="true" /><span>Due date is calculated from the current library policy.</span></div></> : <Prompt icon={Check} text="Select a member and copy to prepare this transaction." />}<button className="button button-primary button-full" type="submit" disabled={!member || !copy || disabled}><BookCheck aria-hidden="true" />Issue selected copy</button></aside>
    </form> : <form action={workspaceMutationAction} className="loan-operation"><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value={mode} /><input type="hidden" name="loanId" value={loanId} /><label className="search-control"><Search aria-hidden="true" /><input value={loanQuery} onChange={(event) => setLoanQuery(event.target.value)} placeholder="Member, title, accession or barcode" /></label><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Member</th><th>Book / copy</th><th>Due date</th><th>Status</th><th>Select</th></tr></thead><tbody>{visibleLoans.map((item) => <tr key={item.id} className={loanId === item.id ? "is-selected" : ""}><td><strong>{item.member}</strong><small>{item.identifier}</small></td><td><strong>{item.title}</strong><small>{item.accession}</small></td><td>{new Date(item.due).toLocaleDateString("en-IN")}</td><td><span className={`status-dot ${item.overdue ? "status-danger" : "status-success"}`}>{item.overdue ? "Overdue" : "Active"}</span></td><td><button type="button" className="button button-small button-secondary" onClick={() => setLoanId(item.id)}>{loanId === item.id ? "Selected" : "Select"}</button></td></tr>)}</tbody></table></div>{loan ? <aside className="loan-confirm"><div><span>{mode === "renew" ? "Renewing" : "Returning"}</span><h2>{loan.title}</h2><p>{loan.member} · {loan.identifier} · {loan.accession}</p></div>{mode === "renew" ? <p><CalendarDays aria-hidden="true" />The new due date is determined by policy after eligibility is rechecked.</p> : <p><RotateCcw aria-hidden="true" />Overdue status and fine policy are evaluated atomically.</p>}<button className="button button-primary" type="submit" disabled={disabled}>{mode === "renew" ? "Renew loan" : "Return copy"}</button></aside> : null}</form>}
  </div>;
}

function SelectionPanel({ step, title, query, onQuery, placeholder, children }: { step: string; title: string; query: string; onQuery: (value: string) => void; placeholder: string; children: React.ReactNode }) { return <section className="selection-panel"><header><span>{step}</span><h2>{title}</h2></header><label className="search-control"><Search aria-hidden="true" /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder={placeholder} /></label>{children}</section>; }
function Prompt({ icon: Icon, text }: { icon: typeof Check; text: string }) { return <div className="inline-empty"><Icon aria-hidden="true" /><span>{text}</span></div>; }
