import { workspaceMutationAction } from "@/app/operator/[libraryCode]/actions";
import { formatMinorUnitsForInput, formatMoneyMinorUnits, moneyInputStep } from "@/lib/i18n/library-localization";
import { MutationRequestId, MutationSubmitButton } from "@/components/operator/mutation-controls";

type BookOption = { id: string; title: string }; type Location = { id: string; display_name: string; location_code: string };
type Copy = { id?: string; book_id?: string; accession_number?: string; barcode?: string; location_id?: string; acquired_on?: string; acquisition_source?: string; replacement_cost_minor?: number; condition_status?: string; operational_state?: string; updated_at?: string };

export function CopyForm({ libraryCode, currencyCode = "INR", localeCode = "en-IN", copy, books, locations, disabled = false, submitLabel = "Save copy" }: { libraryCode: string; currencyCode?: string; localeCode?: string; copy?: Copy; books: BookOption[]; locations: Location[]; disabled?: boolean; submitLabel?: string }) {
  return <form action={workspaceMutationAction} className="popover-form copy-form"><input type="hidden" name="libraryCode" value={libraryCode} /><input type="hidden" name="operation" value="copy_save" />{copy?.id ? <><input type="hidden" name="id" value={copy.id} /><input type="hidden" name="expectedUpdatedAt" value={copy.updated_at} /></> : null}
    <label>Book<select name="bookId" defaultValue={copy?.book_id ?? ""} required disabled={disabled}><option value="" disabled>Select a title</option>{books.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>
    <div className="form-grid"><label>Accession number<input name="accession" defaultValue={copy?.accession_number} required maxLength={120} disabled={disabled} /></label><label>Barcode<input name="barcode" defaultValue={copy?.barcode} maxLength={120} disabled={disabled} /></label></div>
    <label>Shelf<select name="locationId" defaultValue={copy?.location_id ?? ""} disabled={disabled}><option value="">Unassigned</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.display_name} · {item.location_code}</option>)}</select>{!locations.length ? <small>No shelves configured yet. <a href={`/operator/${libraryCode}/inventory/shelves`}>Manage shelves</a></small> : null}</label>
    <div className="form-grid"><label>Acquired on<input name="acquiredOn" type="date" defaultValue={copy?.acquired_on} disabled={disabled} /></label><label>Acquisition source<input name="acquisitionSource" defaultValue={copy?.acquisition_source} maxLength={200} disabled={disabled} /></label><label>Replacement cost ({currencyCode})<input name="replacementCostMinor" type="number" min="0" step={moneyInputStep(currencyCode) ?? "0.01"} defaultValue={formatMinorUnitsForInput(copy?.replacement_cost_minor, currencyCode)} aria-describedby="replacement-cost-hint" disabled={disabled} /><small id="replacement-cost-hint">{copy?.replacement_cost_minor == null ? `Stored in ${currencyCode} minor units when set.` : formatMoneyMinorUnits(copy.replacement_cost_minor, currencyCode, localeCode)}</small></label></div>
    <div className="form-grid"><label>Condition<select name="conditionStatus" defaultValue={copy?.condition_status ?? "good"} disabled={disabled}><option value="good">Good</option><option value="fair">Fair</option><option value="poor">Poor</option></select></label><label>Operational state<select name="operationalState" defaultValue={copy?.operational_state ?? "active"} disabled={disabled}><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="lost">Lost</option><option value="damaged">Damaged</option><option value="withdrawn">Withdrawn</option></select></label></div>
    <MutationRequestId /><MutationSubmitButton idleLabel={submitLabel} pendingLabel={copy?.id ? "Saving…" : "Creating…"} disabled={disabled || !books.length} />
  </form>;
}
