import Link from "next/link";
import { ArrowLeft, BookOpen, ImagePlus, PackageOpen } from "lucide-react";
import { notFound } from "next/navigation";
import { OperatorPageHeader } from "@/components/operator/page-header";
import { getWorkspaceData } from "@/lib/operator/workspace";

type Book = { id: string; title: string; author: string; isbn: string; available: number; total: number; status: string };
export default async function BookWorkspacePage({ params }: { params: Promise<{ libraryCode: string; id: string }> }) {
  const { libraryCode, id } = await params; const data = await getWorkspaceData(libraryCode, "catalogue", "", id); const book = ((data.books ?? []) as Book[]).find((row) => row.id === id) ?? (data.book as Book | undefined); if (!book) notFound();
  return <section className="operator-page-v3 detail-workspace"><Link className="back-link" href={`/operator/${libraryCode}/catalogue`}><ArrowLeft aria-hidden="true" />Catalogue</Link><OperatorPageHeader title={book.title} description={book.author} actions={<button className="button button-primary" type="button" disabled={Boolean(data.demo)}>Save changes</button>} /><div className="detail-hero"><div className="operator-cover detail-cover">{book.title}</div><div><span className={`status-dot ${book.available ? "status-success" : "status-neutral"}`}>{book.available} of {book.total} available</span><dl><div><dt>ISBN</dt><dd>{book.isbn || "Not listed"}</dd></div><div><dt>Record state</dt><dd>{book.status}</dd></div><div><dt>Physical copies</dt><dd>{book.total}</dd></div></dl></div></div><div className="detail-columns"><section><h2><BookOpen aria-hidden="true" />Core identity</h2><div className="form-grid"><label>Title<input defaultValue={book.title} disabled={Boolean(data.demo)} /></label><label>Author<input defaultValue={book.author} disabled={Boolean(data.demo)} /></label><label>ISBN<input defaultValue={book.isbn} disabled={Boolean(data.demo)} /></label><label>Language<select disabled={Boolean(data.demo)} defaultValue="English"><option>English</option><option>Hindi</option><option>Odia</option></select></label></div></section><aside><h2><ImagePlus aria-hidden="true" />Cover</h2><p>JPEG, PNG, or WebP up to 5 MB. Stored privately and signed only after room and book verification.</p><button className="button button-secondary" disabled={Boolean(data.demo)}>Upload cover</button><h2><PackageOpen aria-hidden="true" />Inventory</h2><p>{book.total} physical copies · {book.available} currently lendable</p><Link className="button button-secondary" href={`/operator/${libraryCode}/inventory?q=${encodeURIComponent(book.title)}`}>Open copies</Link></aside></div></section>;
}
