import Link from "next/link";
import { Grid2X2, List, MoreHorizontal } from "lucide-react";
import { Feedback, OperatorPageHeader } from "@/components/operator/page-header";
import { BookForm } from "@/components/operator/book-form";
import { OperatorToolbar } from "@/components/operator/toolbar";
import { getWorkspaceData } from "@/lib/operator/workspace";
import { workspaceMutationAction } from "../actions";

type Book = { id: string; title: string; author: string; isbn: string; available: number; total: number; status: string };
type Ref = { id: string; name: string };
export default async function CataloguePage({ params, searchParams }: { params: Promise<{ libraryCode: string }>; searchParams: Promise<{ q?: string; view?: string; error?: string; success?: string }> }) {
  const [{ libraryCode }, query] = await Promise.all([params, searchParams]); const data = await getWorkspaceData(libraryCode, "catalogue", query.q); const books = (data.books ?? []) as Book[]; const disabled=Boolean(data.demo || data.error);
  return <section className="operator-page-v3"><OperatorPageHeader title="Catalogue" description="Bibliographic records and their real physical-copy availability." actions={<div className="view-switcher"><Link className={query.view !== "grid" ? "is-active" : ""} href={{ query: { ...query, view: "list" } }}><List aria-hidden="true" /></Link><Link className={query.view === "grid" ? "is-active" : ""} href={{ query: { ...query, view: "grid" } }}><Grid2X2 aria-hidden="true" /></Link></div>} /><Feedback error={query.error ?? data.error} success={query.success} /><OperatorToolbar query={query.q} addLabel="Add book"><BookForm libraryCode={libraryCode} publishers={(data.publishers ?? []) as Ref[]} categories={(data.categories ?? []) as Ref[]} subjects={(data.subjects ?? []) as Ref[]} disabled={disabled} submitLabel="Create book" /></OperatorToolbar>
  <details className="settings-section"><summary><strong>Reference data</strong> <span>Authors, publishers, categories, subjects, and shelf locations</span></summary><form action={workspaceMutationAction} className="popover-form form-grid"><input type="hidden" name="libraryCode" value={libraryCode}/><input type="hidden" name="operation" value="reference_save"/><label>Type<select name="kind" defaultValue="author" disabled={disabled}><option value="author">Author</option><option value="publisher">Publisher</option><option value="category">Category</option><option value="subject">Subject</option><option value="location">Location</option></select></label><label>Name<input name="name" required maxLength={160} disabled={disabled}/></label><label>Location code <small>Required only for locations</small><input name="code" maxLength={80} disabled={disabled}/></label><button className="button button-secondary" disabled={disabled}>Save reference</button></form></details>
  {query.view === "grid" ? <div className="operator-book-grid">{books.map((book) => <Link key={book.id} href={`/operator/${libraryCode}/catalogue/${book.id}`}><span className="operator-cover">{book.title}</span><strong>{book.title}</strong><small>{book.author}</small><span className={`status-dot ${book.available ? "status-success" : "status-neutral"}`}>{book.available} of {book.total} available</span></Link>)}</div> : <div className="data-table-wrap"><table className="data-table data-table-catalogue"><thead><tr><th>Title</th><th>Author</th><th>ISBN</th><th>Availability</th><th>Copies</th><th>State</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{books.map((book) => <tr key={book.id}><td><Link href={`/operator/${libraryCode}/catalogue/${book.id}`}><strong>{book.title}</strong></Link></td><td>{book.author}</td><td className="tabular">{book.isbn || "—"}</td><td><span className={`status-dot ${book.available ? "status-success" : "status-neutral"}`}>{book.available ? "Available" : book.total ? "Unavailable" : "No copies"}</span></td><td>{book.available} of {book.total}</td><td>{book.status}</td><td><Link className="icon-button" href={`/operator/${libraryCode}/catalogue/${book.id}`} aria-label={`Open ${book.title}`}><MoreHorizontal aria-hidden="true" /></Link></td></tr>)}</tbody></table>{!books.length && !data.error ? <div className="table-empty">No matching books</div> : null}</div>}</section>;
}
