import type { Metadata } from "next";
import Link from "next/link";
import { Building2, CheckCircle2, ShieldCheck } from "lucide-react";
import { Brand } from "@/components/brand/brand";
import { ThemeToggle } from "@/components/theme/theme-toggle";
import { getOptionalPublicSupabaseEnv } from "@/lib/env/public";
import { createLibraryAction } from "./actions";

export const metadata: Metadata = { title: "Create a library", robots: { index: false, follow: false } };

export default async function CreateLibraryPage({ searchParams }: { searchParams: Promise<{ error?: string; confirmation?: string; name?: string; code?: string; person?: string }> }) {
  const query = await searchParams; const configured = Boolean(getOptionalPublicSupabaseEnv());
  return <main className="onboarding-shell"><header><Brand /><ThemeToggle compact /></header><div className="onboarding-grid"><section className="onboarding-intro"><p>Start a Library Room</p><h1>Give your institution a focused place to discover and operate.</h1><ul><li><Building2 aria-hidden="true" /><span><strong>One room identity</strong> for the public catalogue and staff workspace.</span></li><li><ShieldCheck aria-hidden="true" /><span><strong>Tenant-scoped from the first record</strong>, with no global administrator access.</span></li><li><CheckCircle2 aria-hidden="true" /><span><strong>Short onboarding</strong>, then configure policy and catalogue data inside the workspace.</span></li></ul></section><section className="onboarding-form"><div><span>1</span>Account</div><div><span>2</span>Library</div>{query.confirmation ? <div className="notice notice-success" role="status"><h2>Check your email</h2><p>Confirm your address, then return to finish creating the Library Room.</p></div> : <form action={createLibraryAction}><fieldset disabled={!configured}><legend>Your account</legend><label>Your display name<input name="personName" defaultValue={query.person ?? ""} required maxLength={120} /></label><label>Email<input name="email" type="email" autoComplete="email" /></label><label>Password<input name="password" type="password" autoComplete="new-password" minLength={8} /></label><p>If you are already signed in, GranthSetu uses that verified account.</p></fieldset><fieldset disabled={!configured}><legend>Library Room</legend><label>Institution or library name<input name="displayName" defaultValue={query.name ?? ""} required maxLength={160} /></label><label>Library Code<input className="code-field" name="libraryCode" defaultValue={query.code ?? ""} required minLength={5} maxLength={16} pattern="[A-Za-z0-9](?:[A-Za-z0-9-]{3,14})[A-Za-z0-9]" autoCapitalize="characters" /><small>5–16 letters, numbers, or internal hyphens. The code is public and globally unique.</small></label></fieldset>{query.error ? <p className="notice notice-error" role="alert">{query.error}</p> : null}{!configured ? <p className="notice" role="status">Library creation needs the Supabase environment variables for this deployment.</p> : null}<button className="button button-primary button-full" type="submit" disabled={!configured}>Create Library Room</button></form>}<Link className="back-link" href="/">Back to GranthSetu</Link></section></div></main>;
}
