import { randomUUID } from "node:crypto";
import { requireOperator, hasRole } from "@/lib/auth/authorization";
import { formatInrMinorUnits } from "@/lib/circulation/money";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { assessFineAction, issueLoanAction, renewLoanAction, returnLoanAction, settleFineAction, waiveFineAction } from "@/app/operator/circulation/actions";

type SearchParams = Promise<{ error?: string; success?: string }>;
export default async function CirculationPage({ searchParams }: { searchParams: SearchParams }) {
  const context = await requireOperator();
  const supabase = await createSupabaseServerClient();
  const [{ data: members }, { data: copies }, { data: loans }, { data: fines }, { data: settings }] = await Promise.all([
    supabase.from("members").select("id, member_identifier, display_name, member_kind, status").order("display_name").limit(100),
    supabase.from("book_copies").select("id, accession_number, barcode, operational_state, book_id, books(title, status)").order("accession_number").limit(100),
    supabase.from("loans").select("id, member_id, book_copy_id, issued_at, due_at, returned_at, status, members(display_name, member_identifier), book_copies(accession_number, barcode, books(title))").order("due_at").limit(100),
    supabase.from("fines").select("id, loan_id, assessed_amount_minor, waived_amount_minor, settled_amount_minor, currency_code, loans(member_id, book_copy_id, members(display_name), book_copies(accession_number, books(title)))").order("created_at", { ascending: false }).limit(100),
    supabase.from("library_settings").select("setting_key, value_kind, boolean_value, integer_value, money_minor_value"),
  ]);
  const params = await searchParams;
  const policy = new Map((settings ?? []).map((row) => [row.setting_key, row]));
  const ready = policy.has("default_loan_period_days") && policy.has("checkout_limit") && policy.has("renewal_limit");
  // This is a server-rendered operational snapshot, not client authorization or mutation data.
  // eslint-disable-next-line react-hooks/purity
  const now = Date.now();
  return <section className="operator-page circulation-page" aria-labelledby="circulation-title">
    <p className="auth-kicker">Trusted operations</p><h1 id="circulation-title">Circulation workbench</h1>
    <p className="operator-lede">Issue, return, renew, and account for library items through database-authoritative operations. Every mutation is attributed to your active operator profile.</p>
    {params.error ? <p className="auth-error" role="alert">{params.error}</p> : null}{params.success ? <p className="auth-success" role="status">{params.success}</p> : null}
    {!ready ? <p className="auth-error" role="status">Circulation policy is not configured for this environment. Read-only lookup remains available.</p> : null}
    <div className="circulation-grid">
      <article className="operator-invite"><h2>Issue a book</h2><form className="auth-form" action={issueLoanAction}>
        <label className="auth-field">Member<select name="memberId" required defaultValue=""><option value="" disabled>Select active member</option>{(members ?? []).filter((m) => m.status === "active").map((m) => <option key={m.id} value={m.id}>{m.member_identifier} · {m.display_name}</option>)}</select></label>
        <label className="auth-field">Physical copy<select name="copyId" required defaultValue=""><option value="" disabled>Select active copy</option>{(copies ?? []).filter((c) => c.operational_state === "active" && (Array.isArray(c.books) ? c.books[0]?.status === "active" : c.books?.status === "active")).map((c) => <option key={c.id} value={c.id}>{c.accession_number} · {Array.isArray(c.books) ? c.books[0]?.title : c.books?.title}{c.barcode ? ` · ${c.barcode}` : ""}</option>)}</select></label>
        <label className="auth-field">Notes <input name="notes" maxLength={2000} /></label><input type="hidden" name="requestId" value={randomUUID()} /><button className="button" type="submit" disabled={!ready}>Issue loan</button>
      </form></article>
      <article className="operator-invite"><h2>Look up members and copies</h2><p className="operator-muted">Search-ready identifiers are shown below for Development workbench use. Barcode scanners can type into the copy selector when the final scanner workflow is introduced.</p><div className="lookup-list"><strong>{members?.length ?? 0} members loaded</strong><strong>{copies?.length ?? 0} copies loaded</strong></div></article>
    </div>
    <div className="operator-table-wrap"><table className="operator-table"><caption>Loans</caption><thead><tr><th>Member</th><th>Copy</th><th>Due</th><th>Actions</th></tr></thead><tbody>{(loans ?? []).map((loan) => { const member = Array.isArray(loan.members) ? loan.members[0] : loan.members; const copy = Array.isArray(loan.book_copies) ? loan.book_copies[0] : loan.book_copies; const overdue = loan.status === "active" && new Date(loan.due_at).getTime() < now; return <tr key={loan.id}><th>{member?.display_name ?? "—"}<br /><span className="operator-muted">{member?.member_identifier}</span></th><td>{copy?.accession_number}<br /><span className="operator-muted">{Array.isArray(copy?.books) ? copy?.books[0]?.title : copy?.books?.title}</span></td><td className={overdue ? "circulation-overdue" : ""}>{new Date(loan.due_at).toLocaleDateString("en-IN")} {loan.status === "returned" ? "· Returned" : overdue ? "· Overdue" : ""}</td><td><div className="operator-controls">{loan.status === "active" ? <><form action={returnLoanAction}><input type="hidden" name="loanId" value={loan.id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small" type="submit">Return</button></form><form action={renewLoanAction}><input type="hidden" name="loanId" value={loan.id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small button-quiet" type="submit" disabled={!ready}>Renew</button></form></> : <form action={assessFineAction}><input type="hidden" name="loanId" value={loan.id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small button-quiet" type="submit">Assess fine</button></form>}</div></td></tr>; })}</tbody></table></div>
    <div className="operator-table-wrap"><table className="operator-table"><caption>Fines and account actions</caption><thead><tr><th>Borrower / item</th><th>Assessed</th><th>Waived</th><th>Settled</th><th>Outstanding</th><th>Actions</th></tr></thead><tbody>{(fines ?? []).map((fine) => { const loan = Array.isArray(fine.loans) ? fine.loans[0] : fine.loans; const outstanding = Number(fine.assessed_amount_minor) - Number(fine.waived_amount_minor) - Number(fine.settled_amount_minor); return <tr key={fine.id}><th>{loan?.members?.display_name ?? "—"}<br /><span className="operator-muted">{loan?.book_copies?.accession_number} · {Array.isArray(loan?.book_copies?.books) ? loan?.book_copies?.books[0]?.title : loan?.book_copies?.books?.title}</span></th><td>{formatInrMinorUnits(fine.assessed_amount_minor)}</td><td>{formatInrMinorUnits(fine.waived_amount_minor)}</td><td>{formatInrMinorUnits(fine.settled_amount_minor)}</td><td>{formatInrMinorUnits(outstanding)}</td><td><div className="operator-controls">{outstanding > 0 ? <form className="inline-money-form" action={settleFineAction}><input name="amount" inputMode="decimal" placeholder="INR" aria-label="Settlement amount in INR" required /><input name="note" maxLength={500} placeholder="Note" aria-label="Settlement note" /><input type="hidden" name="fineId" value={fine.id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small" type="submit">Settle</button></form> : null}{hasRole(context, "administrator") && outstanding > 0 ? <form className="inline-money-form" action={waiveFineAction}><input name="amount" inputMode="decimal" placeholder="INR" aria-label="Waiver amount in INR" required /><input name="reason" maxLength={500} placeholder="Reason" aria-label="Waiver reason" required /><input type="hidden" name="fineId" value={fine.id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small button-quiet" type="submit">Waive</button></form> : null}</div></td></tr>; })}</tbody></table></div>
  </section>;
}
