import { randomUUID } from "node:crypto";
import { requireOperator, hasRole } from "@/lib/auth/authorization";
import { formatInrMinorUnits } from "@/lib/circulation/money";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { asOperatorRpcClient } from "@/lib/operator/rpc";
import { assessFineAction, renewLoanAction, returnLoanAction, settleFineAction, waiveFineAction } from "./actions";
import { IssueBookForm } from "./issue-book-form";

type Params = Promise<{ member?: string; copy?: string; loan?: string; fine?: string; error?: string; success?: string }>;
type Member = { member_id: string; member_identifier: string; display_name: string; member_kind: string; status: string; enrollment_label: string | null; roll_number: string | null; active_loans: number; overdue_loans: number };
type Copy = { copy_id: string; title: string; author_names: string; isbn: string | null; accession_number: string; barcode: string | null; location_name: string | null; operational_state: string; available: boolean; on_loan: boolean };
type Loan = { loan_id: string; member_identifier: string; member_name: string; accession_number: string; title: string; barcode: string | null; issued_at: string; due_at: string; returned_at: string | null; status: string };
type Fine = { fine_id: string; loan_id: string; fine_kind: string; member_identifier: string; member_name: string; title: string; accession_number: string; assessed_amount_minor: number; waived_amount_minor: number; settled_amount_minor: number; outstanding_minor: number; reason: string | null };

export default async function CirculationPage({ searchParams }: { searchParams: Params }) {
  const context = await requireOperator();
  const params = await searchParams;
  const supabase = await createSupabaseServerClient();
  const rpc = asOperatorRpcClient(supabase);
  const [memberResult, copyResult, loanResult, fineResult, policyResult] = await Promise.all([
    rpc.rpc("circulation_member_search", { p_query: params.member ?? "", p_limit: 50 }),
    rpc.rpc("circulation_copy_search", { p_query: params.copy ?? "", p_available_only: true, p_limit: 50 }),
    rpc.rpc("circulation_loan_search", { p_query: params.loan ?? "", p_active_only: false, p_limit: 50 }),
    rpc.rpc("circulation_fine_search", { p_query: params.fine ?? "", p_outstanding_only: false, p_limit: 50 }),
    rpc.rpc("operator_policy_context"),
  ]);
  const members = (memberResult.data ?? []) as Member[]; const copies = (copyResult.data ?? []) as Copy[]; const loans = (loanResult.data ?? []) as Loan[]; const fines = (fineResult.data ?? []) as Fine[];
  const policy = (Array.isArray(policyResult.data) ? policyResult.data[0] : policyResult.data) as { overdue_renewal_allowed?: boolean; librarian_waiver_allowed?: boolean } | null;
  const ready = !policyResult.error; const canWaive = hasRole(context, "administrator") || (hasRole(context, "librarian") && Boolean(policy?.librarian_waiver_allowed));
  const issueCandidateContextKey = [params.member ?? "", params.copy ?? "", ...members.map((member) => member.member_id), ...copies.map((copy) => copy.copy_id)].join("|");
  return <section className="operator-page circulation-page" aria-labelledby="circulation-title">
    <p className="auth-kicker">Trusted operations</p><h1 id="circulation-title">Circulation workbench</h1>
    <p className="operator-lede">Search the database first. Results are bounded for safe handling, while trusted RPCs remain the final authority for issue, return, renew, and fine actions.</p>
    {params.error ? <p className="auth-error" role="alert">{params.error}</p> : null}{params.success ? <p className="auth-success" role="status">{params.success}</p> : null}
    {!ready ? <p className="auth-error" role="status">Policy context is unavailable; mutation controls are disabled until the database policy is readable.</p> : null}
    <div className="circulation-grid">
      <IssueBookForm key={issueCandidateContextKey} members={members} copies={copies} ready={ready} requestId={randomUUID()} initialMemberSearch={params.member ?? ""} initialCopySearch={params.copy ?? ""} loanSearch={params.loan ?? ""} fineSearch={params.fine ?? ""} />
      <article className="operator-invite"><h2>Search controls</h2><form className="auth-form" method="get"><label className="auth-field">Member search<input name="member" defaultValue={params.member ?? ""} placeholder="Name, generated ID, roll, grade, section" /></label><label className="auth-field">Copy search<input name="copy" defaultValue={params.copy ?? ""} placeholder="Title, author, ISBN, accession, barcode" /></label><label className="auth-field">Loan / return search<input name="loan" defaultValue={params.loan ?? ""} placeholder="Member, title, accession, barcode" /></label><label className="auth-field">Fine search<input name="fine" defaultValue={params.fine ?? ""} placeholder="Member, title, accession, fine kind" /></label><button className="button button-small" type="submit">Search all workflows</button></form><p className="operator-muted">{policy?.overdue_renewal_allowed ? "Overdue renewals are enabled by policy." : "Overdue renewals are blocked by policy."}</p></article>
    </div>
    <div className="operator-table-wrap"><table className="operator-table"><caption>Member matches ({members.length})</caption><thead><tr><th>Member</th><th>Enrollment</th><th>Borrowing</th><th>Issue</th></tr></thead><tbody>{members.map((member) => <tr key={member.member_id}><th scope="row">{member.display_name}<br /><span className="operator-muted">{member.member_identifier} · {member.member_kind}</span></th><td>{member.enrollment_label ?? "No current enrollment"}{member.roll_number ? ` · Roll ${member.roll_number}` : ""}</td><td>{member.active_loans} active{member.overdue_loans ? ` · ${member.overdue_loans} overdue` : ""}</td><td><span className="operator-muted">Select explicitly in the issue panel above</span></td></tr>)}</tbody></table></div>
    <div className="operator-table-wrap"><table className="operator-table"><caption>Available copy matches ({copies.length})</caption><thead><tr><th>Book</th><th>Copy</th><th>Location</th><th>State</th></tr></thead><tbody>{copies.map((copy) => <tr key={copy.copy_id}><th scope="row">{copy.title}<br /><span className="operator-muted">{copy.author_names}{copy.isbn ? ` · ISBN ${copy.isbn}` : ""}</span></th><td>{copy.accession_number}{copy.barcode ? ` · ${copy.barcode}` : ""}</td><td>{copy.location_name ?? "—"}</td><td>{copy.operational_state}</td></tr>)}</tbody></table></div>
    <div className="operator-table-wrap"><table className="operator-table"><caption>Loans ({loans.length})</caption><thead><tr><th>Member</th><th>Copy</th><th>Due</th><th>Actions</th></tr></thead><tbody>{loans.map((loan) => <tr key={loan.loan_id}><th scope="row">{loan.member_name}<br /><span className="operator-muted">{loan.member_identifier}</span></th><td>{loan.accession_number}<br /><span className="operator-muted">{loan.title}</span></td><td>{new Date(loan.due_at).toLocaleDateString("en-IN")} {loan.status === "returned" ? "· Returned" : "· Active"}</td><td><div className="operator-controls">{loan.status === "active" ? <><form action={returnLoanAction}><input type="hidden" name="loanId" value={loan.loan_id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small" type="submit">Return</button></form><form action={renewLoanAction}><input type="hidden" name="loanId" value={loan.loan_id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small button-quiet" type="submit" disabled={!ready}>Renew</button></form></> : <form action={assessFineAction}><input type="hidden" name="loanId" value={loan.loan_id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small button-quiet" type="submit">Assess fine</button></form>}</div></td></tr>)}</tbody></table></div>
    <div className="operator-table-wrap"><table className="operator-table"><caption>Fines ({fines.length})</caption><thead><tr><th>Borrower / item</th><th>Kind</th><th>Assessed</th><th>Outstanding</th><th>Actions</th></tr></thead><tbody>{fines.map((fine) => <tr key={fine.fine_id}><th scope="row">{fine.member_name}<br /><span className="operator-muted">{fine.member_identifier} · {fine.accession_number} · {fine.title}</span></th><td>{fine.fine_kind}</td><td>{formatInrMinorUnits(fine.assessed_amount_minor)}</td><td>{formatInrMinorUnits(fine.outstanding_minor)}</td><td>{fine.outstanding_minor > 0 ? <div className="operator-controls"><form className="inline-money-form" action={settleFineAction}><input name="amount" inputMode="decimal" placeholder="INR" aria-label="Settlement amount in INR" required /><input name="note" maxLength={500} placeholder="Note" aria-label="Settlement note" /><input type="hidden" name="fineId" value={fine.fine_id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small" type="submit">Settle</button></form>{canWaive ? <form className="inline-money-form" action={waiveFineAction}><input name="amount" inputMode="decimal" placeholder="INR" aria-label="Waiver amount in INR" required /><input name="reason" maxLength={500} placeholder="Reason" aria-label="Waiver reason" required /><input type="hidden" name="fineId" value={fine.fine_id} /><input type="hidden" name="requestId" value={randomUUID()} /><button className="button button-small button-quiet" type="submit">Waive</button></form> : null}</div> : "—"}</td></tr>)}</tbody></table></div>
  </section>;
}
