import { Download, SlidersHorizontal } from "lucide-react";
import { Feedback, OperatorPageHeader } from "@/components/operator/page-header";
import { requireLibraryOperator } from "@/lib/auth/authorization";
import { formatDateOnly, formatLibraryDateTime, formatMoneyMinorUnits } from "@/lib/i18n/library-localization";
import { getReportData, type ReportFilters } from "@/lib/operator/workspace";

const labels: Record<string, string> = { circulation: "Circulation history", overdue: "Overdue loans", popular: "Popular books", members: "Member activity", inventory: "Inventory", fines: "Fines" };
export default async function ReportsPage({ params, searchParams }: { params: Promise<{ libraryCode: string }>; searchParams: Promise<ReportFilters & { error?: string }> }) {
  const [{ libraryCode }, query] = await Promise.all([params, searchParams]); const kind = labels[query.kind ?? ""] ? query.kind! : "circulation";
  const [data, context] = await Promise.all([getReportData(libraryCode, { ...query, kind }), requireLibraryOperator(libraryCode)]);
  const rows = (data.rows ?? []) as Array<Record<string, unknown>>; const columns = Array.from(new Set(rows.flatMap(Object.keys)));
  const exportQuery = new URLSearchParams(Object.entries({ ...query, kind }).filter((entry): entry is [string, string] => typeof entry[1] === "string" && entry[1] !== ""));
  return <section className="operator-page-v3 reports-page"><OperatorPageHeader title="Reports" description="Filtered, room-scoped operational records with matching CSV exports." actions={<a className="button button-secondary" href={`/operator/${libraryCode}/reports/export?${exportQuery}`}><Download aria-hidden="true" />Export CSV</a>} /><Feedback error={query.error ?? data.error} /><form className="report-filters"><SlidersHorizontal aria-hidden="true" /><label>Report<select name="kind" defaultValue={kind}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>From<input type="date" name="from" defaultValue={query.from} /></label><label>To / as of<input type="date" name="to" defaultValue={query.to} /></label><label>Search<input name="q" defaultValue={query.q} placeholder="Member, title, ID…" /></label><label>Inventory state<select name="status" defaultValue={query.status ?? ""}><option value="">All states</option><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="lost">Lost</option><option value="damaged">Damaged</option><option value="withdrawn">Withdrawn</option></select></label><label className="checkbox-field"><input type="checkbox" name="outstanding" value="true" defaultChecked={query.outstanding === "true"}/>Outstanding fines only</label><button className="button button-primary button-small">Apply filters</button></form><section className="report-table"><header><h2>{labels[kind]}</h2><p>{rows.length} matching row{rows.length === 1 ? "" : "s"}. The export uses these same filters.</p></header>{rows.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr>{columns.map((column) => <th key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? row.loan_id ?? row.book_id ?? row.member_id ?? row.fine_id ?? index)}>{columns.map((column) => <td key={column}>{formatValue(column, row[column], row.currency_code, context.currencyCode, context.localeCode, context.timeZone)}</td>)}</tr>)}</tbody></table></div> : <div className="table-empty">No report rows match these filters</div>}</section></section>;
}
function formatValue(column: string, value: unknown, historicalCurrency: unknown, roomCurrency: string, locale: string, timeZone: string) { if (value == null) return "—"; if (column.endsWith("_minor")) return formatMoneyMinorUnits(value as number, typeof historicalCurrency === "string" ? historicalCurrency : roomCurrency, locale); if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}T/.test(value)) return formatLibraryDateTime(value, locale, timeZone); if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value)) return formatDateOnly(value, locale); return String(value); }
