import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, BookOpen, Globe2, Hash } from "lucide-react";
import { notFound } from "next/navigation";
import { Availability } from "@/components/catalogue/availability";
import { BookCover } from "@/components/catalogue/book-cover";
import { getPublicBook, getPublicLibrary } from "@/lib/library/public-data";

export async function generateMetadata({ params }: { params: Promise<{ libraryCode: string; bookId: string }> }): Promise<Metadata> { const { libraryCode, bookId } = await params; const book = await getPublicBook(libraryCode, bookId); return { title: book?.title ?? "Book not found", description: book ? `${book.title} by ${book.authorNames}. Check availability in GranthSetu.` : undefined, robots: book ? undefined : { index: false, follow: false } }; }
export default async function PublicBookPage({ params }: { params: Promise<{ libraryCode: string; bookId: string }> }) { const { libraryCode, bookId } = await params; const [library, book] = await Promise.all([getPublicLibrary(libraryCode), getPublicBook(libraryCode, bookId)]); if (!library || !book) notFound(); const coverUrl = book.hasCover ? `/api/public/libraries/${library.code}/covers/${book.id}` : null; return <article className="book-detail"><Link className="back-link" href={`/l/${library.code}/catalogue`}><ArrowLeft aria-hidden="true" />Catalogue</Link><div className="book-detail-grid"><div className="book-detail-cover"><BookCover title={book.title} author={book.authorNames} coverUrl={coverUrl} priority /></div><div className="book-detail-copy"><p className="book-detail-category">{book.categoryNames.join(" · ") || "Catalogue"}</p><h1>{book.title}</h1>{book.subtitle ? <h2>{book.subtitle}</h2> : null}<p className="book-detail-author">{book.authorNames}</p><Availability book={book} detailed localeCode={library.localeCode} /><div className="book-description"><h2>About this book</h2><p>{book.description ?? "This library has not added a public description for this title."}</p></div><dl className="book-metadata"><div><dt><BookOpen aria-hidden="true" />Publisher</dt><dd>{book.publisherName ?? "Not listed"}{book.publicationYear ? `, ${book.publicationYear}` : ""}</dd></div><div><dt><Globe2 aria-hidden="true" />Language</dt><dd>{book.languageCode ?? "Not listed"}</dd></div><div><dt><Hash aria-hidden="true" />ISBN</dt><dd>{book.isbn ?? "Not listed"}</dd></div></dl>{book.subjectNames.length ? <div className="subject-list" aria-label="Subjects">{book.subjectNames.map((subject) => <span key={subject}>{subject}</span>)}</div> : null}</div></div></article>; }
